paths:
  uploads: uploads
  static: ''
  dam_uploads: ''
  dam_static: ''
  collections: ''
  data: _data
  layouts: _layouts
  includes: _includes
collections_config:
  pages:
    path: ''
    output: true
    filter: strict
    description: ''
    icon: notes
    _editables:
    _inputs:
    _select_data:
    _structures:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default page:
        path:
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        name:
        icon: notes
        preview:
        _editables:
        _inputs:
        _select_data:
        _structures:
        create:
        new_preview_url:
_inputs:
  layout:
    type: text
    hidden: true
    cascade: true
  id:
    type: text
    hidden: true
    cascade: true
  block-content-html:
    type: html
    options:
      allow_resize: true
      allow_custom_markup: false
      remove_custom_markup: false
      initial_height: 320
      italic: true
      format: p h1 h2 h3 a img
      bold: true
      horizontalrule: true
      image: true
      image_size_attributes: true
      link: true
      resize_style: contain
      snippet: false
      styles: /editor.css
    label: Content
    cascade: true
  height:
    type: select
    options:
      allow_empty: true
      values:
        50vh: half-screen min-height
        75vh: three-quarter screen min-height
        90vh: just short of full screen
        100vh: full screen
    cascade: true
  column-width:
    type: select
    options:
      allow_empty: true
      values:
        33%: 1/3 of the page
        50%: 1/2 of the page
  text-alignment:
    type: select
    options:
      allow_empty: false
      values:
        - left
        - center
        - right
    cascade: true

_structures:
  blocks:
    style: modal
    values:
      - label: text block
        value:
          _id: rich_text_block
          text_html: <h1>Let’s CREATE Something</i> BEAUTIFUL Together</h1>
          text-alignment: center
          horizontal-alignment: center
          vertical-alignment: center
          column-width: 50%
          scheme:
            scheme-color: base

  header_links:
    style: modal
    values:
      - label: simple link
        value:
          link: /
          text: home
      - label: link with sublinks
        value:
          text: home
          link: /
          sub_links:
            - text: sublink 1
              link: /
            - text: sublink 2
              link: /
            - text: sublink 3
              link: /
